import type { ReportProjectSource } from "@/lib/reports/report.repository";

export function createReportSourceFixture(): ReportProjectSource {
  const frontend = { code: "FRONTEND" as const, name: "Frontend" };
  const backend = { code: "BACKEND" as const, name: "Backend" };
  const database = { code: "DATABASE" as const, name: "Database" };
  const milestoneId = "10000000-0000-4000-8000-000000000001";
  const capabilityId = "20000000-0000-4000-8000-000000000001";
  return {
    id: "00000000-0000-4000-8000-000000000001",
    code: "ORBIT",
    name: "Orbit Test Project",
    description: "A controlled fixture for report verification.",
    status: "ACTIVE",
    progress: 50,
    startDate: new Date("2026-01-01T00:00:00.000Z"),
    targetDate: new Date("2026-12-31T00:00:00.000Z"),
    milestones: [
      {
        id: milestoneId,
        code: "M01",
        name: "Foundation Delivery",
        businessPurpose: "Establish a secure delivery foundation.",
        status: "IN_PROGRESS",
        progress: 50,
        riskLevel: "MEDIUM",
        deliveryStage: "IN_DEVELOPMENT",
        releaseHorizon: "RELEASE_1",
        sortOrder: 1,
        startDate: new Date("2026-01-01T00:00:00.000Z"),
        dueDate: new Date("2026-06-30T00:00:00.000Z"),
        deliveredScope: "Initial shell",
        remainingScope: "Verification",
        currentBlockers: null,
        nextAction: "Complete verification",
        firstReleaseImpact: "Required for Release 1",
        workItems: [
          {
            id: "30000000-0000-4000-8000-000000000001",
            code: "WI-001",
            name: "Responsive application shell",
            description: "Build the responsive shell.",
            status: "IN_PROGRESS",
            progress: 60,
            riskLevel: "LOW",
            deliveryStage: "IN_DEVELOPMENT",
            nextGate: "Technical Verification",
            startDate: new Date("2026-01-05T00:00:00.000Z"),
            dueDate: new Date("2026-03-01T00:00:00.000Z"),
            blocker: null,
            acceptanceCriteria: "Responsive at all breakpoints.",
            owner: null,
            primaryWorkstream: frontend,
            supportingWorkstreams: [{ workstream: backend }],
          },
          {
            id: "30000000-0000-4000-8000-000000000002",
            code: "WI-002",
            name: "Project data repository",
            description: "Provide normalized persistence.",
            status: "NOT_STARTED",
            progress: 0,
            riskLevel: "HIGH",
            deliveryStage: "NOT_STARTED",
            nextGate: "Development Start",
            startDate: new Date("2026-02-01T00:00:00.000Z"),
            dueDate: new Date("2026-04-01T00:00:00.000Z"),
            blocker: "Database design approval",
            acceptanceCriteria: "Repository tests pass.",
            owner: { displayName: "Casey Engineer" },
            primaryWorkstream: database,
            supportingWorkstreams: [{ workstream: backend }],
          },
        ],
      },
    ],
    sharedCapabilities: [
      {
        id: capabilityId,
        code: "SC-001",
        name: "Authentication & Session Security",
        description: "Canonical authentication capability.",
        status: "IN_PROGRESS",
        progress: 40,
        riskLevel: "MEDIUM",
        deliveryStage: "TECHNICAL_VERIFICATION",
        nextGate: "Business UAT",
        startDate: new Date("2026-01-01T00:00:00.000Z"),
        dueDate: new Date("2026-05-01T00:00:00.000Z"),
        blocker: null,
        acceptanceCriteria: "Sessions are secure.",
        owner: { displayName: "Alex Lead" },
        primaryWorkstream: backend,
        supportingWorkstreams: [{ workstream: frontend }, { workstream: database }],
        milestoneLinks: [
          {
            sourceReference: "Architecture decision",
            dependencyNotes: "Required by foundation",
            isCritical: true,
            milestone: { id: milestoneId, code: "M01", name: "Foundation Delivery" },
          },
        ],
      },
    ],
    risks: [
      {
        id: "40000000-0000-4000-8000-000000000001",
        title: "Database approval delay",
        description: "The schema approval may delay delivery.",
        probability: 3,
        impact: 4,
        severity: "HIGH",
        status: "OPEN",
        mitigation: "Schedule design review.",
        dueDate: new Date("2026-02-15T00:00:00.000Z"),
        owner: null,
        milestone: { code: "M01", name: "Foundation Delivery" },
        workItem: { code: "WI-002", name: "Project data repository" },
        sharedCapability: null,
        primaryWorkstream: database,
      },
    ],
    decisions: [
      {
        id: "50000000-0000-4000-8000-000000000001",
        title: "Approve database design",
        description: "Approve the normalized domain model.",
        requiredBy: new Date("2026-02-10T00:00:00.000Z"),
        recommendedDirection: "Approve the normalized design.",
        status: "PENDING",
        decisionText: null,
        decidedAt: null,
        owner: null,
        milestone: { code: "M01", name: "Foundation Delivery" },
        affectedWorkstreams: [{ workstream: backend }, { workstream: database }],
      },
    ],
    pilotScope: {
      id: "60000000-0000-4000-8000-000000000001",
      name: "Controlled Pilot",
      knownLimitations: "Reporting is read-only.",
      businessSignOffStatus: "PENDING",
      technicalSignOffStatus: "APPROVED",
      finalDecisionStatus: "PENDING",
      finalDecision: null,
      supportOwner: null,
      rollbackOwner: { displayName: "Alex Lead" },
      teams: [
        {
          id: "70000000-0000-4000-8000-000000000001",
          name: "Inbound",
          leadUser: null,
          members: [{ user: { displayName: "Pilot User" } }],
        },
      ],
      capabilities: [
        {
          disposition: "INCLUDED",
          notes: "Required for Pilot",
          sharedCapability: { id: capabilityId, code: "SC-001", name: "Authentication & Session Security" },
        },
      ],
      criteria: [
        {
          id: "80000000-0000-4000-8000-000000000001",
          code: "ENTRY-01",
          type: "ENTRY",
          title: "Security verification complete",
          isRequired: true,
          status: "MET",
          evidence: "Verification passed",
        },
      ],
      issues: [],
    },
  } as unknown as ReportProjectSource;
}
